const axios = require("axios");
const fs = require("fs-extra");
const path = require("path");
const { createCanvas, loadImage, registerFont } = require("canvas");

module.exports.config = {
    name: "spy",
    version: "2.0.0",
    hasPermssion: 0,
    credits: "Saim / Modified for Mirai",
    description: "ইউজারের বিস্তারিত তথ্য সহ একটি নিয়ন স্পাই কার্ড তৈরি করে।",
    commandCategory: "utility",
    usages: "[mention/reply/uid]",
    cooldowns: 5
};

module.exports.run = async function ({ api, event, args, Users, Currencies }) {
    const { threadID, messageID, senderID, mentions, type, messageReply } = event;

    try {
        let targetID;
        if (Object.keys(mentions).length > 0) targetID = Object.keys(mentions)[0];
        else if (type == "message_reply") targetID = messageReply.senderID;
        else targetID = args[0] && !isNaN(args[0]) ? args[0] : senderID;

        api.sendMessage("⚡ আপনার স্পাই কার্ড তৈরি হচ্ছে, দয়া করে অপেক্ষা করুন...", threadID, messageID);

        // ডাটা সংগ্রহ
        const userInfo = await api.getUserInfo(targetID);
        const userStats = await Users.getData(targetID);
        const money = (await Currencies.getData(targetID)).money || 0;
        
        const name = userInfo[targetID].name;
        const gender = userInfo[targetID].gender == 2 ? "Boy 👦" : userInfo[targetID].gender == 1 ? "Girl 👧" : "Unknown 🤷";
        const username = userInfo[targetID].vanity || "No Username";
        const fbUrl = `facebook.com/${targetID}`;

        // ইমেজ তৈরির প্রসেস (Canvas)
        const canvas = createCanvas(500, 700);
        const ctx = canvas.getContext("2d");

        // ব্যাকগ্রাউন্ড কালার
        ctx.fillStyle = "#1a0033";
        ctx.fillRect(0, 0, canvas.width, canvas.height);

        // ইউজার প্রোফাইল পিকচার লোড
        const avatarUrl = `https://graph.facebook.com/${targetID}/picture?width=512&height=512&access_token=6628568379%7Cc1e620fa708a1d5696fb991c1bde5662`;
        let avatar;
        try {
            avatar = await loadImage(avatarUrl);
        } catch (e) {
            avatar = await loadImage("https://i.imgur.com/I3VsBEt.png"); // Default
        }

        // কার্ড ডিজাইন (বর্ডার ও টেক্সট)
        ctx.strokeStyle = "#00ffff";
        ctx.lineWidth = 5;
        ctx.strokeRect(10, 10, 480, 680);

        ctx.drawImage(avatar, 150, 50, 200, 200);

        ctx.fillStyle = "#fff";
        ctx.font = "bold 25px Arial";
        ctx.textAlign = "center";
        ctx.fillText(name, 250, 300);

        ctx.textAlign = "left";
        ctx.font = "20px Arial";
        ctx.fillStyle = "#00ffff";
        ctx.fillText(`🆔 UID: ${targetID}`, 50, 380);
        ctx.fillText(`🌐 Username: ${username}`, 50, 420);
        ctx.fillText(`🚻 Gender: ${gender}`, 50, 460);
        ctx.fillText(`💰 Money: $${money.toLocaleString()}`, 50, 500);
        ctx.fillText(`🌍 Profile: ${fbUrl}`, 50, 540);

        ctx.font = "italic 15px Arial";
        ctx.fillStyle = "#aaaaaa";
        ctx.fillText("©️ Generated by Spy AI", 180, 650);

        const pathImg = path.join(__dirname, "cache", `spy_${targetID}.png`);
        const buffer = canvas.toBuffer();
        fs.writeFileSync(pathImg, buffer);

        return api.sendMessage({
            attachment: fs.createReadStream(pathImg)
        }, threadID, () => fs.unlinkSync(pathImg), messageID);

    } catch (e) {
        console.log(e);
        return api.sendMessage("❌ কার্ড তৈরি করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।", threadID, messageID);
    }
};
